### PR TITLE
build via CircleCi

### PR DESCRIPTION
**Pull request by lsgrep**
* build via CircleCi
* add recaptcha

### CODE REVIEW

**Comment by lacksfish** [comment]
Cool! I see it also adds recaptcha on the login page, good choice.

**Comment by lsgrep** [comment]
LGTM

**Comment by lacksfish** [comment]
ACK, looks good to me 👍 Maybe consider not to pull the API_HOST key from the appconfig, but I'd say the default is what is defined anyways.

**Comment by lsgrep** [comment]
Hmm. About API_HOST, I could not think of a better solution at the moment. I might have to spend some time on this. Thanks for bringing this up though.

**Pull request merged**
